/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-gradient-to-br',
    'bg-gradient-to-r',
    'bg-gradient-to-l',
    'from-blue-50',
    'from-blue-100',
    'from-blue-200',
    'from-blue-500',
    'from-blue-600',
    'from-blue-700',
    'from-purple-50',
    'from-purple-500',
    'from-purple-600',
    'from-green-400',
    'from-green-500',
    'from-green-600',
    'from-emerald-500',
    'via-white',
    'via-purple-500',
    'via-purple-600',
    'to-purple-50',
    'to-purple-100',
    'to-purple-600',
    'to-purple-700',
    'to-blue-600',
    'to-blue-700',
    'to-blue-100',
    'to-pink-50',
    'to-pink-500',
    'to-pink-600',
    'to-emerald-500',
    'to-green-600',
    'animate-pulse',
    'animate-fadeIn',
    'animate-float',
    'bg-clip-text',
    'text-transparent',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
        },
      },
    },
  },
  plugins: [],
}
